print("Lai aprēķināu laukumu nepieciešamai tev figūrai lūdzu nospied burtu kurš tai atbilst")
print("T - ja figūra kaurai vēlies aprēķināt laukumu ir trijstūris")
print("Tr - ja figūra kaurai vēlies aprēķināt laukumu ir trapece")
print("P - ja figūra kaurai vēlies aprēķināt laukumu ir paralelograms")
print("Ta - ja figūra kaurai vēlies aprēķināt laukumu ir taisnstūris")
print("K - ja figūra kaurai vēlies aprēķināt laukumu ir kvadrāts")
print("R - ja figūra kaurai vēlies aprēķināt laukumu ir riņķis")
print("ievadi savu burtu:")
x = input()